# Generated by Django 5.0.14 on 2026-09-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROLE_CHANGED', 'Role changed'), ('USER_SUSPENDED', 'User suspended'), ('USER_REINSTATED', 'User reinstated'), ('JOB_FLAGGED', 'Job flagged'), ('JOB_REMOVED', 'Job removed'), ('JOB_RESTORED', 'Job restored')], max_length=30)),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('JOB', 'Job posting')], max_length=10)),
                ('target_id', models.IntegerField()),
                ('target_label', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
